# Miyadaiku config file

# Base URL of the site
site_url: https://aoirint.com/blog/

# Title of the site
site_title: えやみぐさ

# Default language code
lang: ja-JP

# Default charset
charset: utf-8

# Default timezone
timezone: Asia/Tokyo

copyright: Copyright © 2020 aoirint.

favicon: /static/icons/avatar.png

ga_tracking_id: UA-157155944-5

# List of site theme
themes:
  - miyadaiku.themes.sample.blog
  - miyadaiku_theme_fontawesome
