# Miyadaiku config file

# Base URL of the site
site_url: https://blog.aoirint.com

# Title of the site
site_title: えやみぐさ

# Default language code
lang: ja-JP

# Default charset
charset: utf-8

# Default timezone
timezone: Asia/Tokyo

copyright: Copyright © 2020 aoirint.

favicon: /favicon.ico

ga_tracking_id: UA-157155944-5

twitter_name: aoirint
github_name: aoirint


# List of site theme
themes:
  - aoirint_miyadaiku_theme_blog
